export const SET_LOADING = "SET_LOADING";
export const SET_MESSAGE = "SET_MESSAGE";
export const SET_SENTMESSAGE = "SET_SENTMESSAGE";
export const SET_AIANSWER = "SET_AIANSWER";
export const ADD_TO_CHATLOG = "ADD_TO_CHATLOG";
export const SET_ISEXPANDED = "SET_ISEXPANDED";
